import { describe, expect, it } from "vitest";
import ExcelJS from "exceljs";
import { logbookPdf, logbookXlsx } from "./documents";
import { LOGBOOK_COLUMNS, type LogbookRow } from "./export";

const header = ["Dr Riya Singh — City Dental College", "Spec · This year", "Generated by OraMedha - Resident on 27 Sep 2026"];
const row = (i: number, name = `Patient ${i}`): LogbookRow => ["10 Sep 2026", String(1000 + i), name, "36", "Type A", "Stage 1", "Complete", ""];

describe("logbookPdf", () => {
  it("embeds a font that can draw Hindi/Marathi names, and numbers every page", async () => {
    const rows = [row(0, "राहुल शर्मा"), row(1, "श्रेया क्षीरसागर"), ...Array.from({ length: 60 }, (_, i) => row(i + 2))];
    const pdf = await logbookPdf(header, rows);
    const text = pdf.toString("latin1");
    expect(text.startsWith("%PDF")).toBe(true);
    // The embedded font, not a built-in one that has no Devanagari.
    expect(text).toMatch(/NotoSansDevanagari/);
    expect(text).not.toMatch(/\/BaseFont \/Helvetica/);
    // 62 rows don't fit on one A4 landscape page.
    const pages = (text.match(/\/Type \/Page\b/g) ?? []).length;
    expect(pages).toBeGreaterThanOrEqual(2);
  });

  it("still makes a document when there's nothing to list", async () => {
    const pdf = await logbookPdf(header, []);
    expect(pdf.toString("latin1").startsWith("%PDF")).toBe(true);
  });
});

describe("logbookXlsx", () => {
  it("has the header, the column titles and one row per entry — names in any script", async () => {
    const buf = await logbookXlsx(header, [row(0, "राहुल शर्मा"), row(1)]);
    const wb = new ExcelJS.Workbook();
    await wb.xlsx.load(buf as unknown as ArrayBuffer);
    const ws = wb.getWorksheet("Logbook")!;
    expect(ws.getRow(1).getCell(1).value).toBe(header[0]);
    expect((ws.getRow(5).values as unknown[]).slice(1)).toEqual([...LOGBOOK_COLUMNS]);
    expect(ws.getRow(6).getCell(3).value).toBe("राहुल शर्मा");
    expect(ws.rowCount).toBe(7);
  });
});
