import { formatShortDate } from "@/lib/dates";
import type { LogEntry } from "./count";
import { APP_NAME } from "@/lib/brand/name";

/**
 * The logbook as exported to Excel and PDF: one row per stage done in a
 * visit. Built from LogEntry, which has no phone field — patient phone
 * numbers can't end up in an export.
 */
export const LOGBOOK_COLUMNS = ["Date", "OPD no.", "Patient", "Tooth", "Case type", "Stage", "Result", "Special case"] as const;

export type LogbookRow = [string, string, string, string, string, string, string, string];

/** "10 Sep 2026" — exports always carry the year. */
export function exportDate(date: string): string {
  // formatShortDate adds the year whenever "today" is in another year.
  return formatShortDate(date, "0000-01-01");
}

export function logbookRow(e: LogEntry): LogbookRow {
  return [
    exportDate(e.visitDate),
    e.opdNumber ?? "",
    e.patientName,
    e.tooth ?? "",
    e.caseTypeName,
    e.stageName,
    e.outcome === "complete" ? "Complete" : "Partial",
    e.isSpecial ? "Yes" : "",
  ];
}

export type ExportHeader = { pgName: string; college: string; specialty: string; periodLabel: string; caseType: string | null };

export function headerLines(h: ExportHeader, generatedOn: string): string[] {
  return [
    `${h.pgName} — ${h.college}`,
    `${h.specialty} · ${h.periodLabel}${h.caseType ? ` · ${h.caseType}` : ""}`,
    `Generated by ${APP_NAME} on ${generatedOn}`,
  ];
}

/** "logbook-2026-09-01-to-2026-09-30.xlsx" — no names in file names. */
export function exportFileName(period: { from: string | null; to: string | null }, ext: "xlsx" | "pdf"): string {
  const range = period.from || period.to ? `${period.from ?? "start"}-to-${period.to ?? "today"}` : "all-time";
  return `logbook-${range}.${ext}`;
}
