import { describe, expect, it } from "vitest";
import { LOGBOOK_COLUMNS, exportDate, exportFileName, headerLines, logbookRow } from "./export";
import type { LogEntry } from "./count";

const e: LogEntry = {
  visitId: "v",
  visitDate: "2026-09-10",
  createdAt: "2026-09-10T05:00:00Z",
  patientId: "p",
  patientName: "Rahul Sharma",
  opdNumber: "1247",
  caseId: "c",
  caseTypeId: "A",
  caseTypeName: "Type A",
  tooth: "46",
  stageId: "s",
  stageName: "Stage 1",
  stageOrder: 1,
  outcome: "complete",
  isSpecial: true,
  deleted: false,
};

describe("logbook export", () => {
  it("one row per stage, in column order, with the year", () => {
    expect(LOGBOOK_COLUMNS).toHaveLength(8);
    expect(logbookRow(e)).toEqual(["10 Sep 2026", "1247", "Rahul Sharma", "46", "Type A", "Stage 1", "Complete", "Yes"]);
    expect(logbookRow({ ...e, outcome: "partial", isSpecial: false, opdNumber: null, tooth: null })).toEqual([
      "10 Sep 2026", "", "Rahul Sharma", "", "Type A", "Stage 1", "Partial", "",
    ]);
    expect(exportDate("2025-01-02")).toBe("2 Jan 2025");
  });

  it("never includes a phone number (there's no column and no field for it)", () => {
    const withPhone = { ...e, patientPhone: "9876543210" } as LogEntry;
    expect(logbookRow(withPhone).join(" ")).not.toContain("9876543210");
    expect(LOGBOOK_COLUMNS.join(" ").toLowerCase()).not.toMatch(/phone|mobile/);
  });

  it("header names the PG, college, specialty and range", () => {
    expect(
      headerLines({ pgName: "Dr Riya Singh", college: "City Dental College", specialty: "Spec", periodLabel: "This month", caseType: null }, "27 Sep 2026"),
    ).toEqual(["Dr Riya Singh — City Dental College", "Spec · This month", "Generated by OraMedha - Resident on 27 Sep 2026"]);
  });

  it("file names carry the range, never a name", () => {
    expect(exportFileName({ from: "2026-09-01", to: "2026-09-30" }, "xlsx")).toBe("logbook-2026-09-01-to-2026-09-30.xlsx");
    expect(exportFileName({ from: null, to: null }, "pdf")).toBe("logbook-all-time.pdf");
  });
});
